### ISSUE TITLE
README.MD - Missing Step?

### ISSUE THREAD

**Issue by justindirose** [joebuhlig/jekyll-theme-collected#1]
The doc currently states:
> Add the following to your site's _config.yml:
> ```remote_theme: jekyll-theme-collected```

Should it rather read, since ```jekyll-remote-themes``` requires a username:
> Add the following to your site's _config.yml:
> ```remote_theme: joebuhlig/jekyll-theme-collected```

Or should it read:
> Fork the theme
> Add the following to your site's _config.yml:
> ```remote_theme: <YOUR GITHUB USERNAME>/jekyll-theme-collected```

Not sure best practice, but I had to dink around with it to figure it out :)

**Comment by joebuhlig** [comment]
It should be ```joebuhlig/jekyll-theme-collected```

Sorry about that. Updating now.

**Comment by joebuhlig** [comment]
Corrected here:

https://github.com/joebuhlig/jekyll-theme-collected/commit/379fec40ea92b1514cdc652dbe3846e5e7d9d6d5
